.PHONY: all clean

PRJ_DIR = $(CURDIR)
export PRJ_DIR

UTILS_DIR = $(PRJ_DIR)/utils
export UTILS_DIR

ZLOG_DIR = $(PRJ_DIR)/zlog
export ZLOG_DIR

JSONC_DIR = $(PRJ_DIR)/json-c
export JSONC_DIR

MQTTC_DIR = $(PRJ_DIR)/mqtt-c
export MQTTC_DIR

APP_DIR = $(PRJ_DIR)/app
export APP_DIR

HTTPD_DIR = $(PRJ_DIR)/httpd
export HTTPD_DIR

subdirs = utils zlog json-c mqtt-c httpd app main

include $(PRJ_DIR)/make/make.subdirs

