EXE = 
LIB = libapp.a

INC_DIRS =  ../include \
			$(ZLOG_DIR)/include \
			$(UTILS_DIR)/include \
			$(JSONC_DIR)/include \
			$(MQTTC_DIR)/include \
			$(HTTPD_DIR)/include

LINK_LIBS = 

include $(PRJ_DIR)/make/make.rule
